// File: /backend/CineNiche.Auth/Services/StytchService.cs
using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.Extensions.Options;
using CineNiche.Auth.Configuration;
using System.Text.Json.Serialization;

namespace CineNiche.Auth.Services
{
    public class StytchService : IStytchService
    {
        private readonly HttpClient _httpClient;
        private readonly StytchConfig _config;
        private readonly ITokenService _tokenService;
        
        public StytchService(
            HttpClient httpClient, 
            IOptions<StytchConfig> config,
            ITokenService tokenService)
        {
            _config = config.Value;
            
            // Log Stytch configuration (but mask the secret)
            Console.WriteLine($"StytchService - Project ID: {_config.ProjectId}");
            Console.WriteLine($"StytchService - Base URL: {_config.BaseUrl}");
            
            // Basic URL setup
            httpClient.BaseAddress = new Uri(_config.BaseUrl);
            
            // Add authorization header
            var credentials = Convert.ToBase64String(
                Encoding.UTF8.GetBytes($"{_config.ProjectId}:{_config.Secret}")
            );
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", credentials);
            
            Console.WriteLine($"StytchService - Authorization Header Set: Basic {credentials.Substring(0, 10)}...");
            
            // Ensure JSON content
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            
            _httpClient = httpClient;
            _tokenService = tokenService;
        }
        
        public async Task<AuthResult> AuthenticateByEmailAsync(string email, string password)
        {
            try
            {
                var requestData = new
                {
                    email,
                    password
                };
                
                var content = new StringContent(JsonSerializer.Serialize(requestData), Encoding.UTF8, "application/json");
                var response = await _httpClient.PostAsync("passwords/authenticate", content);
                
                if (response.IsSuccessStatusCode)
                {
                    var responseContent = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<StytchAuthResponse>(responseContent, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                    
                    if (result != null)
                    {
                        return new AuthResult
                        {
                            Success = true,
                            UserId = result.UserId,
                            SessionId = result.SessionId,
                            Token = null // Token will be generated by controller using TokenService
                        };
                    }
                }
                
                return new AuthResult 
                { 
                    Success = false, 
                    Error = "Authentication failed" 
                };
            }
            catch (Exception ex)
            {
                return new AuthResult 
                { 
                    Success = false, 
                    Error = $"Authentication error: {ex.Message}" 
                };
            }
        }
        
        public async Task<AuthResult> AuthenticateByTokenAsync(string token)
        {
            try
            {
                var requestData = new
                {
                    token
                };
                
                var content = new StringContent(JsonSerializer.Serialize(requestData), Encoding.UTF8, "application/json");
                var response = await _httpClient.PostAsync("magic_links/authenticate", content);
                
                if (response.IsSuccessStatusCode)
                {
                    var responseContent = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<StytchAuthResponse>(responseContent, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                    
                    if (result != null)
                    {
                        return new AuthResult
                        {
                            Success = true,
                            UserId = result.UserId,
                            SessionId = result.SessionId,
                            Token = null // Token will be generated by controller using TokenService
                        };
                    }
                }
                
                return new AuthResult 
                { 
                    Success = false, 
                    Error = "Token authentication failed" 
                };
            }
            catch (Exception ex)
            {
                return new AuthResult 
                { 
                    Success = false, 
                    Error = $"Token authentication error: {ex.Message}" 
                };
            }
        }
        
        public async Task<UserResult> CreateUserAsync(string email, string password, string firstName, string lastName)
        {
            try
            {
                // Step 1: Create the user (without password)
                var createUserRequest = new
                {
                    email,
                    name = new
                    {
                        first_name = firstName,
                        last_name = lastName
                    }
                };
                
                Console.WriteLine($"CreateUserAsync Request: POST to {_httpClient.BaseAddress}users");
                var createUserJson = JsonSerializer.Serialize(createUserRequest);
                Console.WriteLine($"Request Body: {createUserJson}");
                
                var createUserContent = new StringContent(createUserJson, Encoding.UTF8, "application/json");
                var createUserResponse = await _httpClient.PostAsync("users", createUserContent);
                
                var createUserResponseContent = await createUserResponse.Content.ReadAsStringAsync();
                Console.WriteLine($"CreateUserAsync Response Status: {createUserResponse.StatusCode}");
                Console.WriteLine($"Response Content: {createUserResponseContent}");
                
                if (!createUserResponse.IsSuccessStatusCode)
                {
                    return new UserResult 
                    { 
                        Success = false, 
                        Error = $"User creation failed. Status: {createUserResponse.StatusCode}, Content: {createUserResponseContent}" 
                    };
                }
                
                string? userId = null;
                
                try
                {
                    // Extract the user_id from the response
                    using JsonDocument doc = JsonDocument.Parse(createUserResponseContent);
                    userId = doc.RootElement.GetProperty("user_id").GetString();
                    Console.WriteLine($"Extracted user_id directly from JSON: {userId}");
                    
                    if (string.IsNullOrEmpty(userId))
                    {
                        return new UserResult 
                        { 
                            Success = false, 
                            Error = "Failed to find user_id in response" 
                        };
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Error extracting user_id: {ex.Message}");
                    return new UserResult 
                    { 
                        Success = false, 
                        Error = $"Failed to find user_id in response: {ex.Message}" 
                    };
                }
                
                // Instead of trying to set the password via API, we'll skip that step for now
                // and return success. In a real application, you might want to use a different
                // Stytch flow for setting passwords or ask the user to set a password via email
                
                Console.WriteLine("User created successfully, skipping password setup (needs to be done through a different flow)");
                
                // Return successful result with user details
                return new UserResult
                {
                    Success = true,
                    UserId = userId,
                    Email = email,
                    FirstName = firstName,
                    LastName = lastName,
                    EmailVerified = false
                };
            }
            catch (Exception ex)
            {
                Console.WriteLine($"CreateUserAsync Exception: {ex.Message}");
                Console.WriteLine($"Stack Trace: {ex.StackTrace}");
                if (ex.InnerException != null)
                {
                    Console.WriteLine($"Inner Exception: {ex.InnerException.Message}");
                }
                
                return new UserResult 
                { 
                    Success = false, 
                    Error = $"User creation error: {ex.Message}" 
                };
            }
        }
        
        public async Task<UserResult> GetUserByIdAsync(string userId)
        {
            try
            {
                var response = await _httpClient.GetAsync($"users/{userId}");
                
                if (response.IsSuccessStatusCode)
                {
                    var responseContent = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<StytchUserResponse>(responseContent, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                    
                    if (result != null)
                    {
                        return new UserResult
                        {
                            Success = true,
                            UserId = result.UserId,
                            Email = result.Email,
                            FirstName = result.Name?.FirstName,
                            LastName = result.Name?.LastName,
                            EmailVerified = result.EmailVerified
                        };
                    }
                }
                
                return new UserResult 
                { 
                    Success = false, 
                    Error = "User not found" 
                };
            }
            catch (Exception ex)
            {
                return new UserResult 
                { 
                    Success = false, 
                    Error = $"Get user error: {ex.Message}" 
                };
            }
        }
        
        public async Task<UserResult> GetUserByEmailAsync(string email)
        {
            try
            {
                var requestData = new
                {
                    email
                };
                
                var content = new StringContent(JsonSerializer.Serialize(requestData), Encoding.UTF8, "application/json");
                var response = await _httpClient.PostAsync("users/search", content);
                
                if (response.IsSuccessStatusCode)
                {
                    var responseContent = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<StytchUserSearchResponse>(responseContent, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                    
                    if (result != null && result.Users.Count > 0)
                    {
                        var user = result.Users[0];
                        return new UserResult
                        {
                            Success = true,
                            UserId = user.UserId,
                            Email = user.Email,
                            FirstName = user.Name?.FirstName,
                            LastName = user.Name?.LastName,
                            EmailVerified = user.EmailVerified
                        };
                    }
                }
                
                return new UserResult 
                { 
                    Success = false, 
                    Error = "User not found" 
                };
            }
            catch (Exception ex)
            {
                return new UserResult 
                { 
                    Success = false, 
                    Error = $"Search user error: {ex.Message}" 
                };
            }
        }
        
        public async Task<EmailResult> SendPasswordResetEmailAsync(string email)
        {
            try
            {
                var requestData = new
                {
                    email,
                    login_redirect_url = _config.LoginRedirectUrl
                };
                
                var content = new StringContent(JsonSerializer.Serialize(requestData), Encoding.UTF8, "application/json");
                var response = await _httpClient.PostAsync("passwords/email/reset/start", content);
                
                if (response.IsSuccessStatusCode)
                {
                    var responseContent = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<StytchEmailResponse>(responseContent, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                    
                    if (result != null)
                    {
                        return new EmailResult
                        {
                            Success = true,
                            Email = email,
                            RequestId = result.RequestId
                        };
                    }
                }
                
                return new EmailResult 
                { 
                    Success = false, 
                    Error = "Failed to send password reset email" 
                };
            }
            catch (Exception ex)
            {
                return new EmailResult 
                { 
                    Success = false, 
                    Error = $"Password reset error: {ex.Message}" 
                };
            }
        }
        
        public async Task<EmailResult> SendEmailVerificationAsync(string email)
        {
            try
            {
                var requestData = new
                {
                    email,
                    login_redirect_url = _config.LoginRedirectUrl
                };
                
                var content = new StringContent(JsonSerializer.Serialize(requestData), Encoding.UTF8, "application/json");
                var response = await _httpClient.PostAsync("emails/verification/start", content);
                
                if (response.IsSuccessStatusCode)
                {
                    var responseContent = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<StytchEmailResponse>(responseContent, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                    
                    if (result != null)
                    {
                        return new EmailResult
                        {
                            Success = true,
                            Email = email,
                            RequestId = result.RequestId
                        };
                    }
                }
                
                return new EmailResult 
                { 
                    Success = false, 
                    Error = "Failed to send verification email" 
                };
            }
            catch (Exception ex)
            {
                return new EmailResult 
                { 
                    Success = false, 
                    Error = $"Email verification error: {ex.Message}" 
                };
            }
        }
        
        public async Task<AuthResult> VerifyEmailAsync(string token)
        {
            try
            {
                var requestData = new
                {
                    token
                };
                
                var content = new StringContent(JsonSerializer.Serialize(requestData), Encoding.UTF8, "application/json");
                var response = await _httpClient.PostAsync("emails/verification/confirm", content);
                
                if (response.IsSuccessStatusCode)
                {
                    var responseContent = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<StytchAuthResponse>(responseContent, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                    
                    if (result != null)
                    {
                        return new AuthResult
                        {
                            Success = true,
                            UserId = result.UserId,
                            SessionId = result.SessionId,
                            Token = null // Token will be generated by controller using TokenService
                        };
                    }
                }
                
                return new AuthResult 
                { 
                    Success = false, 
                    Error = "Email verification failed" 
                };
            }
            catch (Exception ex)
            {
                return new AuthResult 
                { 
                    Success = false, 
                    Error = $"Email verification error: {ex.Message}" 
                };
            }
        }
        
        public async Task<AuthResult> ResetPasswordAsync(string token, string newPassword)
        {
            try
            {
                var requestData = new
                {
                    token,
                    password = newPassword
                };
                
                var content = new StringContent(JsonSerializer.Serialize(requestData), Encoding.UTF8, "application/json");
                var response = await _httpClient.PostAsync("passwords/reset", content);
                
                if (response.IsSuccessStatusCode)
                {
                    var responseContent = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<StytchAuthResponse>(responseContent, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                    
                    if (result != null)
                    {
                        return new AuthResult
                        {
                            Success = true,
                            UserId = result.UserId,
                            SessionId = result.SessionId,
                            Token = null // Token will be generated by controller using TokenService
                        };
                    }
                }
                
                return new AuthResult 
                { 
                    Success = false, 
                    Error = "Password reset failed" 
                };
            }
            catch (Exception ex)
            {
                return new AuthResult 
                { 
                    Success = false, 
                    Error = $"Password reset error: {ex.Message}" 
                };
            }
        }
        
        public async Task<bool> RevokeSessionAsync(string sessionId)
        {
            try
            {
                var requestData = new
                {
                    session_id = sessionId
                };
                
                var content = new StringContent(JsonSerializer.Serialize(requestData), Encoding.UTF8, "application/json");
                var response = await _httpClient.PostAsync("sessions/revoke", content);
                
                return response.IsSuccessStatusCode;
            }
            catch
            {
                return false;
            }
        }
        
        public async Task<SessionResult> GetSessionAsync(string sessionId)
        {
            try
            {
                var response = await _httpClient.GetAsync($"sessions/{sessionId}");
                
                if (response.IsSuccessStatusCode)
                {
                    var responseContent = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<StytchSessionResponse>(responseContent, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                    
                    if (result != null)
                    {
                        return new SessionResult
                        {
                            Success = true,
                            SessionId = result.SessionId,
                            UserId = result.UserId,
                            Active = result.Status == "active"
                        };
                    }
                }
                
                return new SessionResult 
                { 
                    Success = false, 
                    Error = "Session not found or invalid" 
                };
            }
            catch (Exception ex)
            {
                return new SessionResult 
                { 
                    Success = false, 
                    Error = $"Session retrieval error: {ex.Message}" 
                };
            }
        }
        
        // Private response classes to deserialize Stytch API responses
        private class StytchAuthResponse
        {
            [JsonPropertyName("user_id")]
            public string? UserId { get; set; }
            
            [JsonPropertyName("session_id")]
            public string? SessionId { get; set; }
            
            [JsonPropertyName("email_verified")]
            public bool EmailVerified { get; set; }
        }
        
        private class StytchUserResponse
        {
            [JsonPropertyName("user_id")]
            public string? UserId { get; set; }
            
            [JsonPropertyName("email")]
            public string? Email { get; set; }
            
            [JsonPropertyName("email_verified")]
            public bool EmailVerified { get; set; }
            
            [JsonPropertyName("name")]
            public NameInfo? Name { get; set; }
            
            public class NameInfo
            {
                [JsonPropertyName("first_name")]
                public string? FirstName { get; set; }
                
                [JsonPropertyName("last_name")]
                public string? LastName { get; set; }
            }
        }
        
        private class StytchUserSearchResponse
        {
            [JsonPropertyName("users")]
            public List<StytchUserResponse> Users { get; set; } = new List<StytchUserResponse>();
        }
        
        private class StytchEmailResponse
        {
            [JsonPropertyName("request_id")]
            public string? RequestId { get; set; }
            
            [JsonPropertyName("email")]
            public string? Email { get; set; }
        }
        
        private class StytchSessionResponse
        {
            [JsonPropertyName("session_id")]
            public string? SessionId { get; set; }
            
            [JsonPropertyName("user_id")]
            public string? UserId { get; set; }
            
            [JsonPropertyName("status")]
            public string? Status { get; set; }
        }

        public async Task<OAuthRedirectResult> GetOAuthRedirectUrlAsync(string provider, bool signup, string redirectUrl)
{
    try
    {
        var requestData = new
        {
            provider_type = provider,
            redirect_url = redirectUrl,
            login_redirect_url = redirectUrl,
            signup_redirect_url = redirectUrl
        };
        
        var content = new StringContent(JsonSerializer.Serialize(requestData), Encoding.UTF8, "application/json");
        var response = await _httpClient.PostAsync("oauth/start", content);
        
        if (response.IsSuccessStatusCode)
        {
            var responseContent = await response.Content.ReadAsStringAsync();
            
            // Parse from JSON directly since we don't have a class for this response
            using JsonDocument doc = JsonDocument.Parse(responseContent);
            string url = doc.RootElement.GetProperty("url").GetString() ?? string.Empty;
            string state = doc.RootElement.GetProperty("state").GetString() ?? string.Empty;
            
            return new OAuthRedirectResult
            {
                Success = true,
                RedirectUrl = url,
                State = state
            };
        }
        
        return new OAuthRedirectResult
        {
            Success = false,
            Error = $"Failed to get OAuth URL. Status: {response.StatusCode}"
        };
    }
    catch (Exception ex)
    {
        Console.WriteLine($"OAuth URL generation error: {ex.Message}");
        return new OAuthRedirectResult
        {
            Success = false,
            Error = $"OAuth URL generation error: {ex.Message}"
        };
    }
}

public async Task<OAuthAuthResult> ExchangeOAuthCodeAsync(string code, string state)
{
    try
    {
        var requestData = new
        {
            token = code,
            state_token = state
        };
        
        var content = new StringContent(JsonSerializer.Serialize(requestData), Encoding.UTF8, "application/json");
        var response = await _httpClient.PostAsync("oauth/authenticate", content);
        
        if (response.IsSuccessStatusCode)
        {
            var responseContent = await response.Content.ReadAsStringAsync();
            
            // Parse the response to get user information
            using JsonDocument doc = JsonDocument.Parse(responseContent);
            
            string userId = doc.RootElement.GetProperty("user_id").GetString() ?? string.Empty;
            string sessionId = doc.RootElement.GetProperty("session_id").GetString() ?? string.Empty;
            
            // Extract email and name if available
            string email = string.Empty;
            string firstName = string.Empty;
            string lastName = string.Empty;
            
            if (doc.RootElement.TryGetProperty("user", out JsonElement userElement))
            {
                if (userElement.TryGetProperty("emails", out JsonElement emailsElement) && 
                    emailsElement.GetArrayLength() > 0)
                {
                    email = emailsElement[0].GetProperty("email").GetString() ?? string.Empty;
                }
                
                if (userElement.TryGetProperty("name", out JsonElement nameElement))
                {
                    firstName = nameElement.TryGetProperty("first_name", out JsonElement firstNameElement) ? 
                        firstNameElement.GetString() ?? string.Empty : string.Empty;
                        
                    lastName = nameElement.TryGetProperty("last_name", out JsonElement lastNameElement) ? 
                        lastNameElement.GetString() ?? string.Empty : string.Empty;
                }
            }
            
            return new OAuthAuthResult
            {
                Success = true,
                UserId = userId,
                SessionId = sessionId,
                Email = email,
                FirstName = firstName,
                LastName = lastName
            };
        }
        
        return new OAuthAuthResult
        {
            Success = false,
            Error = $"OAuth authentication failed. Status: {response.StatusCode}"
        };
    }
    catch (Exception ex)
    {
        Console.WriteLine($"OAuth authentication error: {ex.Message}");
        return new OAuthAuthResult
        {
            Success = false,
            Error = $"OAuth authentication error: {ex.Message}"
        };
    }
}
    }
}